### ISSUE TITLE
Project cannot be built

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [manidesto/android-garage#2]
I had to remove the twitter related lines from the gradle file, but now it just says:

> Error:Execution failed for task ':app:compileDebugKotlinAfterJava'.
> 
> > Compilation error. See log for more details

**Comment by okmanideep** [comment]
@AndroidDeveloperLB If you are looking for the scrolling demo project, I've extracted it as a seperate [repo](https://www.github.com/manidesto/scrolling-demo)

**Comment by okmanideep** [comment]
@AndroidDeveloperLB I suggest you do a clean first and then do a gradle sync and then try building the project

**Comment by AndroidDeveloperLB** [comment]
The scrolling demo works, but here it doesn't work.
re-building (or clean+build) doesn't help.
BTW, your minSdk is 21 ... That's very high today ... Had to try on emulator for now

**Comment by okmanideep** [comment]
@AndroidDeveloperLB apologies for the high minSdk but this is my garage/experiments repo. I don't intend to release this to the public. So I just chose 21 for convenience.

I don't think you have to remove the twitter lines from build.gradle for the app to build, try keeping those lines and building?

**Comment by AndroidDeveloperLB** [comment]
If I don't remove the twitter lines, I get this error:

> Error:(4, 0) Could not get unknown property 'TWITTER_BEARER_TOKEN' for project ':app' of type org.gradle.api.Project.
> <a href="openFile:C:\Users\user\Desktop\android-garage-master\app\build.gradle">Open File</a>

**Comment by okmanideep** [comment]
@AndroidDeveloperLB should work now. The app will build but you won't be able to see any tweets because it is not built with a valid twitter token. Alternatively, you can click the scrolling demo icon in your launcher and get the scrolling-demo.

**Comment by AndroidDeveloperLB** [comment]
I actually got to this repo from a scrolling demo I wanted to try, but then I go this issue and decided to report about it. Later you provided fixes for a new repo. Now I don't get what I'm supposed to see on this sample app (I see white screen) ...
:)

**Comment by okmanideep** [comment]
@AndroidDeveloperLB even I was wondering that :P

**Comment by AndroidDeveloperLB** [comment]
Sorry for this. You are invited to check out my repos, if you wish:
https://github.com/AndroidDeveloperLB?tab=repositories
